name: weirdhost-auto-add-time
on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 1 点执行，可根据需要调整
  workflow_dispatch:      # 支持手动触发

jobs:
  add_time:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 拉取仓库代码
      - uses: actions/checkout@v4

      # 2️⃣ 设置 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ 安装依赖（Playwright + aiohttp）
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install playwright aiohttp
          playwright install --with-deps chromium

      # 4️⃣ 运行 weirdhost-auto 脚本
      - name: Run weirdhost-auto
        env:
          # 登录 WeirdHost
          PTERODACTYL_EMAIL: ${{ secrets.PTERODACTYL_EMAIL }}
          PTERODACTYL_PASSWORD: ${{ secrets.PTERODACTYL_PASSWORD }}
          SERVER_URL: ${{ secrets.SERVER_URL }}          # 可选，默认脚本已设默认值
          # Telegram 通知
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python main.py

