name: weirdhost-auto-add-time
on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 1 点执行
  workflow_dispatch:

jobs:
  add_time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install playwright aiohttp
          playwright install --with-deps chromium

      - name: Run weirdhost-auto
        env:
          PTERODACTYL_EMAIL: ${{ secrets.PTERODACTYL_EMAIL }}
          PTERODACTYL_PASSWORD: ${{ secrets.PTERODACTYL_PASSWORD }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python main.py
